sudo: required
services:
  - docker

before_install:
  - docker build -t exoplusplus/boots .

script:
  - docker run exoplusplus/boots 

deploy: 
  provider: azure_web_apps
  username: $user
  password: $pass

